apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        # To keep container running on K8s
        # or else below line also fine
        # command: ["/bin/sh", "-ec", "sleep 3600"]
        command: 
          - bin/sh
          - -c
          - "sleep 3600"
        envFrom:
          - secretRef:
            name: app-password
        volumeMounts:
          - name: any-app
            mountPath: /app
      volumes:
        - name: any-name
          secret:
            secretName: app-password
status: {}
